vich_uploader:
    db_driver: orm

    mappings:
       employe:
           uri_prefix: /images/employe
           upload_destination: '%kernel.project_dir%/public/images/employe'
           namer: Vich\UploaderBundle\Naming\OrignameNamer

           inject_on_load:   false
           delete_on_update: true
           delete_on_remove: true
